---
title: "RNA velocity on VASA-seq"
author: "@vivekbhr"
date: "01.08.2019"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    theme: spacelab
---

```{r docSetup, echo = FALSE, bootstrap.show.code = FALSE, dev = "png", bootstrap.show.message=FALSE}
## knitrBoostrap and device chunk options
library('knitr')
opts_chunk$set(bootstrap.show.code = FALSE, dev = "png")
```

```{r barcodeRank, echo = FALSE, eval = TRUE}
## find empty barcodes (cells) using inflection point
getRanks <- function(spliced, unspliced) {
  bc_rank <- DropletUtils::barcodeRanks(spliced)
  bc_uns <- DropletUtils::barcodeRanks(unspliced)

  tibble(rank = bc_rank$rank, total = bc_rank$total, matrix = "spliced") %>%
    bind_rows(tibble(rank = bc_uns$rank, total = bc_uns$total, matrix = "unspliced")) %>%
    distinct() %>%
    ggplot(aes(total, rank, color = matrix)) +
    geom_line() +
    geom_vline(xintercept = metadata(bc_rank)$knee, color = "blue", linetype = 2) +
    geom_vline(xintercept = metadata(bc_rank)$inflection, color = "green", linetype = 2) +
    geom_vline(xintercept = metadata(bc_uns)$knee, color = "purple", linetype = 3) +
    geom_vline(xintercept = metadata(bc_uns)$inflection, color = "cyan", linetype = 3) +
    annotate("text", y = c(1000, 1000, 500, 500),
             x = 1.5 * c(metadata(bc_rank)$knee, metadata(bc_rank)$inflection,
                         metadata(bc_uns)$knee, metadata(bc_uns)$inflectio),
             label = c("knee (s)", "inflection (s)", "knee (u)", "inflection (u)"),
             color = c("blue", "green", "purple", "cyan")) +
    scale_x_log10() +
    scale_y_log10() +
    labs(y = "Rank", x = "Total UMI counts") +
    theme_bw()
  return(bc_rank)
}
```

```{r loadCount, echo = FALSE, eval = TRUE}
dirs <- list.dirs("velocity_quant", full.names = FALSE, recursive = FALSE)

all_data <- lapply(dirs, function(dir) {
  dat <- BUSpaRse::read_velocity_output(spliced_dir = file.path("velocity_quant", dir, "spliced_counts"),
                                        spliced_name = "spliced",
                                        unspliced_dir = file.path("velocity_quant", dir, "unspliced_counts"),
                                        unspliced_name = "unspliced")
  return(dat)
  })
names(all_data) <- dirs
all_data <- lapply(all_data, function(x) {
  x$spliced <- x$spliced[,colnames(x$spliced) %in% colnames(x$unspliced)]
  x$unspliced <- x$unspliced[,colnames(x$unspliced) %in% colnames(x$spliced)]
  return(x)
})
colnums <- sapply(all_data, function(x) ncol(x$spliced), simplify = TRUE)
colnums <- min(colnums)
lapply(all_data, function(x) sum(x$unspliced@x) / (sum(x$unspliced@x) + sum(x$spliced@x)))
```


```{r mergeMatrix, echo = FALSE, eval = TRUE}
sf <- lapply(all_data, function(x) return(x$spliced)) %>% Reduce(cbind, .)
uf <- lapply(all_data, function(x) return(x$unspliced)) %>% Reduce(cbind, .)
prefix <- rep(dirs, each = colnums)

colnames(sf) %<>% paste(prefix, . , sep = "_")
colnames(uf) %<>% paste(prefix, . , sep = "_")

## Summary
tot_count <- Matrix::colSums(sf)
summary(tot_count)
```

```{r filterbarcodes, echo = FALSE, eval = TRUE}
sf_barcodeRanks <- getRanks(sf, uf)
barcodes_touse <- colnames(sf)[tot_count > metadata(sf_barcodeRanks)$inflection]

# Remove genes that aren't detected
tot_genes <- Matrix::rowSums(sf)
genes_use <- rownames(sf)[tot_genes > 0]
sf <- sf[genes_use, barcodes_touse]
uf <- uf[genes_use, barcodes_touse]
print(paste0("After filtering, ", length(genes_use), " genes and ",
             length(barcodes_touse), " barcodes were kept"))
```

```{r seuratCreate, echo = FALSE, eval = TRUE}
## Create Seurat object for sf and uf
seu <- Seurat::CreateSeuratObject(sf, assay = "sf") %>%
  Seurat::SCTransform(assay = "sf", new.assay.name = "spliced")
# uf
seu[["uf"]] <- Seurat::CreateAssayObject(uf)
seu <- Seurat::SCTransform(seu, assay = "uf", new.assay.name = "unspliced")

## add sample metadata
seu <- AddMetaData(seu, gsub("(.*)_[A-Z]*", "\\1", colnames(seu)),
                   col.name = "sample")

## make feature plot
cols_use <- c("nCount_sf", "nFeature_sf", "nCount_uf", "nFeature_uf")

#pdf("Vlnplot_normCounts_spliced.pdf", width = 6, height = 12)
VlnPlot(seu, cols_use, pt.size = 0.1, ncol = 1, group.by = "sample")
#dev.off()
```


```{r elbow, echo = FALSE, eval = TRUE}
DefaultAssay(seu) <- "spliced"
seu <- RunPCA(seu, verbose = FALSE, npcs = 70)
ElbowPlot(seu, ndims = 70)
```


```{r pca, echo = FALSE, eval = TRUE}
DimPlot(seu, reduction = "pca",
        group.by = "sample", pt.size = 0.5, label = TRUE, repel = TRUE) +
  scale_color_brewer(type = "qual", palette = "Set2")
```


```{r umap, echo = FALSE, eval = TRUE}
set.seed(4837)
um <- umap(Embeddings(seu, reduction = "pca")[, 1:50], init = "random")
rownames(um) <- colnames(sf)
colnames(um) <- c("UMAP_1", "UMAP_2")
seu[["umap"]] <- CreateDimReducObject(embeddings = um, assay = "spliced", key = "umap_")
DimPlot(seu, reduction = "umap", group.by = "sample",
        pt.size = 0.5, label = TRUE, repel = TRUE) +
        scale_color_brewer(type = "qual", palette = "Set2")
```


```{r umap2, echo = FALSE, eval = TRUE}
seu <- FindNeighbors(seu, verbose = FALSE) %>%
  FindClusters(resolution = 1, verbose = FALSE) # Louvain
DimPlot(seu, pt.size = 0.5, reduction = "umap")
```



```{r}
#pdf("umap_louvain_spliced.pdf", width = 8, height = 6, onefile = FALSE)
DimPlot(seu, reduction = "umap",
        group.by = "sample", pt.size = 0.5, label = TRUE, repel = TRUE) +
  scale_color_brewer(type = "qual", palette = "Set2")
#dev.off()
```


```{r velocity, echo = FALSE, eval = TRUE}
seu <- RunVelocity(seu, ncores = 10, reduction = "umap", verbose = FALSE)
cell_pal <- function(cell_cats, pal_fun) {
  categories <- sort(unique(cell_cats))
  pal <- setNames(pal_fun(length(categories)), categories)
  pal[cell_cats]
}

cell_colors <- cell_pal(seu$sample, scales::brewer_pal("qual", "Set2"))
cell_colors_clust <- cell_pal(seu$seurat_clusters, scales::hue_pal())
names(cell_colors) <- names(cell_colors_clust) <- colnames(sf)

#pdf("velocity_on_umap.pdf")
cc_umap <- show.velocity.on.embedding.cor(emb = Embeddings(seu, "umap"),
                                          vel = Tool(seu, slot = "RunVelocity"),
                                          n.cores = 50, show.grid.flow = TRUE,
                                          grid.n = 50, cell.colors = cell_colors,
                                          cex = 0.5, cell.border.alpha = 0,
                                          arrow.scale = 2, arrow.lwd = 0.75,
                                          xlab = "UMAP1", ylab = "UMAP2")
#dev.off()
```


```{r saveData, echo = FALSE, eval = TRUE}
saveRDS(seu, file = "velocity_seuratObject.Rds")
sink("sessionInfo.txt")
sessionInfo()
sink()
```
